name: Reorganize Files

on:
  push:
    branches:
      - main

jobs:
  reorganize:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Create organized structure
        run: |
          echo "Initial directory contents:"
          find . -type f -exec echo "Found file: {}" \;
          
          # Create new directory structure
          mkdir -p compass/cogs
          
          echo "\nCopying Python files to cogs:"
          find . -type f -name "*.py" ! -name "bot.py" ! -path "./compass/*" -exec echo "Copying to cogs: {}" \; -exec cp {} compass/cogs/ \;
          
          echo "\nCopying files to compass root:"
          find . -type f -name "bot.py" ! -path "./compass/*" -exec echo "Copying bot.py: {}" \; -exec cp {} compass/ \; || echo "No bot.py found"
          find . -type f -name "*.json" ! -path "./compass/*" -exec echo "Copying json: {}" \; -exec cp {} compass/ \; || echo "No json files found"
          find . -type f -name "README.md" ! -path "./compass/*" -exec echo "Copying README: {}" \; -exec cp {} compass/ \; || echo "No README.md found"
          find . -type f -name "requirements.txt" ! -path "./compass/*" -exec echo "Copying requirements: {}" \; -exec cp {} compass/ \; || echo "No requirements.txt found"
          
          echo "\nFinal compass directory contents:"
          ls -R compass/

      - name: Push to compass-official repository
        run: |
          cd compass
          echo "Contents of compass directory:"
          ls -la
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update from main repository" || echo "Nothing to commit"
          git branch -M main
          git remote add official https://${{ secrets.PAT_TOKEN }}@github.com/lordfalcon787/compass-official.git
          git push -f official main || echo "Push failed with: $?"
