name: Reorganize Files

on:
  push:
    branches:
      - main

jobs:
  reorganize:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Create organized structure
        run: |
          echo "Current directory contents:"
          ls -la
          
          # Create new directory structure
          mkdir -p compass/cogs
          
          # Move all Python files except bot.py to cogs folder
          shopt -s nullglob  # Handle case when no .py files exist
          for file in *.py; do
            if [ "$file" != "bot.py" ] && [ -f "$file" ]; then
              mv "$file" compass/cogs/
            fi
          done
          
          # Move bot.py and json files to compass folder
          mv bot.py compass/ 2>/dev/null || true
          mv *.json compass/ 2>/dev/null || true
          mv README.md compass/ 2>/dev/null || true
          mv requirements.txt compass/ 2>/dev/null || true

      - name: Push to compass-official repository
        run: |
          cd compass
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update from main repository"
          git remote add official https://${{ secrets.PAT_TOKEN }}@github.com/lordfalcon787/compass-official.git
          git push -f official main
