name: Reorganize Files

on:
  push:
    branches:
      - main

jobs:
  reorganize:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Create organized structure
        run: |
          echo "Initial directory contents:"
          ls -la
          
          # Create new directory structure
          mkdir -p compass/cogs
          
          # Copy instead of move to debug
          echo "Copying files..."
          cp -v *.py compass/cogs/ 2>/dev/null || true
          cp -v bot.py compass/ 2>/dev/null || true
          cp -v *.json compass/ 2>/dev/null || true
          cp -v README.md compass/ 2>/dev/null || true
          cp -v requirements.txt compass/ 2>/dev/null || true
          
          echo "Final compass directory contents:"
          ls -R compass/

      - name: Push to compass-official repository
        run: |
          cd compass
          echo "Contents of compass directory:"
          ls -la
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update from main repository" || echo "Nothing to commit"
          git branch -M main
          git remote add official https://${{ secrets.PAT_TOKEN }}@github.com/lordfalcon787/compass-official.git
          git push -f official main
