name: Reorganize Files

on:
  push:
    branches:
      - main

jobs:
  reorganize:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Create organized structure
        run: |
          mkdir -p compass/cogs
          find . -type f -name "*.py" ! -name "bot.py" ! -path "./compass/*" -exec cp {} compass/cogs/ \;
          find . -type f -name "bot.py" ! -path "./compass/*" -exec cp {} compass/ \;
          find . -type f -name "*.json" ! -name "items.json" ! -name "settings.json" ! -path "./compass/*" -exec cp {} compass/ \;
          find . -type f -name "README.md" ! -path "./compass/*" -exec cp {} compass/ \;
          find . -type f -name "requirements.txt" ! -path "./compass/*" -exec cp {} compass/ \;
          find . -type f -name "times.ttf" ! -path "./compass/*" -exec cp {} compass/ \;
          find . -type f -name "config.json" ! -path "./compass/*" -exec cp {} compass/ \;

      - name: Push to compass-official repository
        run: |
          cd compass
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git reset config.json  # Unstage config.json
          git commit -m "Update from main repository"
          git branch -M main
          git remote add official https://${{ secrets.PAT_TOKEN }}@github.com/lordfalcon787/compass-official.git
          git push -f official main
          git add config.json  # Stage config.json
          git commit -m "Add config.json"
          git push -f official main
