name: Reorganize Files

on:
  push:
    branches:
      - main

jobs:
  reorganize:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Create organized structure
        run: |
          echo "Initial directory contents:"
          ls -la
          
          # Create new directory structure
          mkdir -p compass/cogs
          
          # First copy everything to cogs except bot.py
          find . -maxdepth 1 -name "*.py" ! -name "bot.py" -exec cp {} compass/cogs/ \;
          
          # Copy specific files to compass root
          cp bot.py compass/ || echo "No bot.py found"
          cp *.json compass/ || echo "No json files found"
          cp README.md compass/ || echo "No README.md found"
          cp requirements.txt compass/ || echo "No requirements.txt found"
          
          echo "Final compass directory contents:"
          ls -R compass/

      - name: Push to compass-official repository
        run: |
          cd compass
          echo "Contents of compass directory:"
          ls -la
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update from main repository" || echo "Nothing to commit"
          git branch -M main
          git remote add official https://${{ secrets.PAT_TOKEN }}@github.com/lordfalcon787/compass-official.git
          git push -f official main || echo "Push failed with: $?"
